name: Deploy Docker App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << EOF
            set -e
            cd ~

            if [ ! -d JAVA-SPRINGBOT-PROJECT-New ]; then
              git clone https://github.com/patilcloud11/JAVA-SPRINGBOT-PROJECT-New.git
            fi

            cd JAVA-SPRINGBOT-PROJECT-New
            git pull origin main

            docker stop backend || true
            docker rm backend || true
            docker stop frontend || true
            docker rm frontend || true

            docker build -t spring-backend ./backend
            docker build -t streamlit-frontend ./frontend

            docker run -d --name backend -p 8084:8084 spring-backend
            docker run -d --name frontend -p 8501:8501 streamlit-frontend
          EOF
