#1 name: CI-CD Docker Deploy

# on:
#   push:
#     branches:
#       - main
#   workflow_dispatch:

# jobs:
#   build-and-deploy:
#     runs-on: ubuntu-latest

#     env:
#       BACKEND_IMAGE: springboot-backend
#       FRONTEND_IMAGE: react-frontend

#     steps:

      # ==============================
      # ✅ Clone Source Code (git clone equivalent)
      # ==============================
      - name: Checkout Repository
        uses: actions/checkout@v4

      # ==============================
      # Setup Java for Spring Boot
      # ==============================
      # - name: Set up JDK
      #   uses: actions/setup-java@v4
      #   with:
      #     distribution: 'temurin'
      #     java-version: '17'

      # ==============================
      # Setup NodeJS for Frontend
      # ==============================
      # - name: Setup NodeJS
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: '18'

      # ==============================
      # Build Backend
      # ==============================
      # - name: Build Backend
      #   working-directory: ./backend
      #   run: |
      #     chmod +x mvnw || true
      #     ./mvnw clean package -DskipTests || mvn clean package -DskipTests

      # ==============================
      # Build Frontend
      # ==============================
      # - name: Build Frontend
      #   working-directory: ./frontend
      #   run: |
      #     npm install
      #     npm run build

      # ==============================
      # Docker Build Backend
      # ==============================
      #2 - name: Docker Build Backend Image
      #   working-directory: ./backend
      #   run: docker build -t $BACKEND_IMAGE:latest .

      # ==============================
      # Docker Build Frontend Image
      # ==============================
      #3 - name: Docker Build Frontend Image
      #   working-directory: ./frontend
      #   run: docker build -t $FRONTEND_IMAGE:latest .

      # # ==============================
      # # Run Docker Compose (Deploy)
      # # ==============================
      # - name: Run Containers
      #   working-directory: ./compose
        run: |
          docker compose down || true
          docker compose up -d --build
